name: video_ultra_player_example
description: Demonstrates how to use the video_ultra_player plugin.
publish_to: 'none'

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  video_ultra_player:
    path: ../

  cupertino_icons: ^1.0.8
  image_picker: ^1.2.2
  file_picker: ^11.0.2
  gal: ^2.3.1
  path_provider: ^2.1.5

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/clip_a.mp4
    - assets/clip_b.mp4
    - assets/still.png
