name: video_ultra_player
description: Native gapless timeline player plugin backed by platform video composition and a single Flutter texture.
version: 2.0.5
repository: https://github.com/andrelucassvt/video-ultra-player
issue_tracker: https://github.com/andrelucassvt/video-ultra-player/issues

environment:
  sdk: ^3.11.5
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.andre.video_ultra_player
        pluginClass: VideoUltraPlayerPlugin
      ios:
        pluginClass: VideoUltraPlayerPlugin
