import 'package:flutter/foundation.dart';

/// Horizontal alignment of a multi-line text overlay.
enum TimelineTextAlign { left, center, right }

/// An immutable descriptor for a text overlay burned into the composed
/// timeline, identical in the preview and the exported MP4.
///
/// [start] and [end] define the visibility window on the timeline (the
/// overlay is visible in `[start, end)`; the native layer clamps [end] by the
/// total timeline duration). [x] and [y] are the center of the text in
/// normalized frame coordinates (`(0, 0)` is the top-left corner, `(1, 1)` is
/// the bottom-right). [fontSize] is a fraction of the video height so the
/// overlay scales with the output resolution.
///
/// [fontPath] takes precedence over [fontFamily] when both are provided.
/// When [backgroundColor] is `0x00000000` (transparent) no background box is
/// drawn.
@immutable
class TimelineTextOverlay {
  /// Creates a [TimelineTextOverlay].
  ///
  /// [end] must be greater than [start] (not enforceable by an assert in a
  /// const constructor — `Duration` comparisons are not constant expressions).
  /// [x] and [y] must be in `[0.0, 1.0]`; [fontSize] must be in `(0.0, 1.0]`;
  /// [opacity] must be in `[0.0, 1.0]`.
  const TimelineTextOverlay({
    required this.id,
    required this.text,
    required this.start,
    required this.end,
    required this.x,
    required this.y,
    this.rotationDegrees = 0,
    required this.fontSize,
    this.color = 0xFFFFFFFF,
    this.fontFamily,
    this.fontPath,
    this.backgroundColor = 0x00000000,
    this.opacity = 1.0,
    this.textAlign = TimelineTextAlign.center,
  }) : assert(x >= 0.0 && x <= 1.0),
       assert(y >= 0.0 && y <= 1.0),
       assert(fontSize > 0.0 && fontSize <= 1.0),
       assert(opacity >= 0.0 && opacity <= 1.0);

  /// Unique identifier generated by the app, used to update or remove the
  /// overlay.
  final String id;

  /// Text content (multi-line via `\n`).
  final String text;

  /// Start of the visibility window on the timeline.
  final Duration start;

  /// End of the visibility window. Clamped by the total timeline duration;
  /// the overlay is visible in `[start, end)`.
  final Duration end;

  /// Center of the text in normalized frame coordinates in `[0.0, 1.0]`
  /// (`0,0` is the top-left corner).
  final double x;

  /// Center of the text in normalized frame coordinates in `[0.0, 1.0]`
  /// (`0,0` is the top-left corner).
  final double y;

  /// Rotation of the overlay in degrees. Default is `0`.
  final double rotationDegrees;

  /// Font size as a fraction of the video height, in `(0.0, 1.0]`.
  final double fontSize;

  /// ARGB color of the text. Default is opaque white (`0xFFFFFFFF`).
  final int color;

  /// Name of a system font family. Ignored when [fontPath] is provided.
  final String? fontFamily;

  /// Absolute path to a custom `.ttf`/`.otf` font file. Takes precedence over
  /// [fontFamily]. Falls back to the system font when invalid or missing.
  final String? fontPath;

  /// ARGB color of the background box. A transparent value (`0x00000000`)
  /// means no background is drawn.
  final int backgroundColor;

  /// Opacity of the overlay in `[0.0, 1.0]`. Default is fully opaque (`1.0`).
  final double opacity;

  /// Horizontal alignment of multi-line text. Default is [TimelineTextAlign.center].
  final TimelineTextAlign textAlign;

  /// Serialises this [TimelineTextOverlay] to a JSON-compatible map for the
  /// method channel. Durations are expressed in milliseconds. Optional fields
  /// are omitted when `null`.
  Map<String, dynamic> toJson() => <String, dynamic>{
    'id': id,
    'text': text,
    'startMs': start.inMilliseconds,
    'endMs': end.inMilliseconds,
    'x': x,
    'y': y,
    'rotationDegrees': rotationDegrees,
    'fontSize': fontSize,
    'color': color,
    if (fontFamily != null) 'fontFamily': fontFamily,
    if (fontPath != null) 'fontPath': fontPath,
    'backgroundColor': backgroundColor,
    'opacity': opacity,
    'textAlign': textAlign.name,
  };

  /// Returns a copy with the given fields replaced.
  TimelineTextOverlay copyWith({
    String? id,
    String? text,
    Duration? start,
    Duration? end,
    double? x,
    double? y,
    double? rotationDegrees,
    double? fontSize,
    int? color,
    String? fontFamily,
    String? fontPath,
    int? backgroundColor,
    double? opacity,
    TimelineTextAlign? textAlign,
  }) => TimelineTextOverlay(
    id: id ?? this.id,
    text: text ?? this.text,
    start: start ?? this.start,
    end: end ?? this.end,
    x: x ?? this.x,
    y: y ?? this.y,
    rotationDegrees: rotationDegrees ?? this.rotationDegrees,
    fontSize: fontSize ?? this.fontSize,
    color: color ?? this.color,
    fontFamily: fontFamily ?? this.fontFamily,
    fontPath: fontPath ?? this.fontPath,
    backgroundColor: backgroundColor ?? this.backgroundColor,
    opacity: opacity ?? this.opacity,
    textAlign: textAlign ?? this.textAlign,
  );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TimelineTextOverlay &&
          id == other.id &&
          text == other.text &&
          start == other.start &&
          end == other.end &&
          x == other.x &&
          y == other.y &&
          rotationDegrees == other.rotationDegrees &&
          fontSize == other.fontSize &&
          color == other.color &&
          fontFamily == other.fontFamily &&
          fontPath == other.fontPath &&
          backgroundColor == other.backgroundColor &&
          opacity == other.opacity &&
          textAlign == other.textAlign;

  @override
  int get hashCode => Object.hash(
    id,
    text,
    start,
    end,
    x,
    y,
    rotationDegrees,
    fontSize,
    color,
    fontFamily,
    fontPath,
    backgroundColor,
    opacity,
    textAlign,
  );
}
